export enum ActionTypes {
    ADD_BROWSER_DIRECTORY = 'ADD_BROWSER_DIRECTORY',
    BROWSER_DIRECTORY_LOAD_STARTED = 'BROWSER_DIRECTORY_LOAD_STARTED',
    SET_BROWSER_PHOTOS = 'SET_BROWSER_PHOTOS',
    ADD_BROWSER_PHOTOS = 'ADD_BROWSER_PHOTOS',
    TOGGLE_SELECT_BROWSER_PHOTO = 'TOGGLE_SELECT_BROWSER_PHOTO',
    SET_BROWSER_VISIBILITY_FILTER = 'SET_BROWSER_VISIBILITY_FILTER',
    CHANGE_POST_ITEM_ORDER = 'CHANGE_POST_ITEM_ORDER',
}
